name: Docker Image CI

on:
  workflow_run:
    workflows: ["Sync Repository"] # Der Name deines Sync-Workflows
    types:
      - completed # Auslösen, wenn der Workflow abgeschlossen ist

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # Nur ausführen, wenn der vorherige Workflow erfolgreich war

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Build the Docker images
        run: docker-compose build

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push the Docker images
        run: |
          docker tag perplexicaai_perplexica-frontend ghcr.io/grafkoxlp/perplexicaai:latest && \
          docker push ghcr.io/grafkoxlp/perplexicaai:latest
