name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Build the Docker image
        run: docker-compose build

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push the Docker images
        run: |
          docker tag perplexica/perplexica-backend ghcr.io/grafkoxlp/perplexicaai:latest && \
          docker push ghcr.io/grafkoxlp/perplexicaai:latest
