name: Sync Repository

on:
  schedule:
    - cron: '0 0 * * 0' # Läuft jeden Sonntag um Mitternacht
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Sync with Original Repo
        run: |
          git config --global user.email "herschelleon@gmail.com"
          git config --global user.name "Leon"
          
          git remote add upstream https://github.com/ItzCrazyKns/Perplexica.git
          git fetch upstream
          git checkout master
          git merge upstream/master --allow-unrelated-histories
          git push origin master
