name: Sync Repository

on:
  schedule:
    - cron: '0 0 * * 0' # Läuft jeden Sonntag um Mitternacht
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Sync with Original Repo
        run: |
          git config --global user.email "herschelleon@gmail.com"
          git config --global user.name "Leon"
          
          git remote add upstream https://github.com/ItzCrazyKns/Perplexica.git
          git fetch upstream
          git checkout master
          
          # Versuche, die Änderungen zu mergen, aber ignoriere Konflikte
          git merge upstream/master --strategy-option theirs --allow-unrelated-histories
          
          # Konflikte, falls vorhanden, werden so überschrieben
          git add .
          git commit -m "Resolve merge conflicts by favoring upstream changes"
          
          git push origin master
